name: Build
on:
  push:
    paths-ignore:
      - "**/README.md"

jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          host: linux
          target: desktop
          arch: linux_gcc_64
          cache: true

      - name: CMake configure
        run: cmake --preset clang

      - name: CMake build
        run: cmake --build build-clang --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact-linux
          path: ${{ github.workspace }}/build-clang/src/Release/QtQuickPlayground
          if-no-files-found: warn
          overwrite: true

  Build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install build tools
        run: brew install ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          host: mac
          target: desktop
          arch: clang_64
          cache: true

      - name: CMake configure
        run: cmake --preset clang

      - name: CMake build
        run: cmake --build build-clang --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact-macos
          path: ${{ github.workspace }}/build-clang/src/Release/QtQuickPlayground.dmg
          compression-level: 0
          if-no-files-found: warn
          overwrite: true

  Build-Win64:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          cache: true

      - name: Setup MSVC environment
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64 -HostArch amd64 -SkipAutomaticLocation
          "PATH=$env:PATH" >> $env:GITHUB_ENV
          "INCLUDE=$env:INCLUDE" >> $env:GITHUB_ENV
          "LIB=$env:LIB" >> $env:GITHUB_ENV
          "LIBPATH=$env:LIBPATH" >> $env:GITHUB_ENV

      - name: CMake configure
        run: cmake --preset cl

      - name: CMake build
        run: cmake --build build-cl --config Release

      - name: Zip deployment directory
        run: Compress-Archive -Path build-cl/src/Release/* -DestinationPath QtQuickPlayground-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact-windows
          path: ${{ github.workspace }}/QtQuickPlayground-windows.zip
          compression-level: 0
          if-no-files-found: warn
          overwrite: true
